### ISSUE TITLE
Once jupyterlab is installed in one conda environment, it can prevent notebooks from opening in clean env

### ISSUE THREAD

**Issue by michaelpacer** [jupyter/jupyterlab#312]
I have jupyterlab set up in another environment, and when I tried to start a clean env for a tutorial today (that didn't install `jupyterlab`), 

    [W 08:49:48.542 NotebookApp] Error loading server extension jupyterlab
        Traceback (most recent call last):
          File "/Users/cocosci/Jupyter/notebook/notebook/notebookapp.py", line 1162, in init_server_extensions
            mod = importlib.import_module(modulename)
          File "/Users/cocosci/anaconda3/envs/parallel_tutorial/lib/python3.5/importlib/__init__.py", line 126, in import_module
            return _bootstrap._gcd_import(name[level:], package, level)
          File "<frozen importlib._bootstrap>", line 986, in _gcd_import
          File "<frozen importlib._bootstrap>", line 969, in _find_and_load
          File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
        ImportError: No module named 'jupyterlab'

I ran into this error just after it would shut down any kernel's that I opened with error :
    
    [W 08:50:29.912 NotebookApp] KernelRestarter: restart failed
    [W 08:50:29.912 NotebookApp] Kernel 3d08514d-4d39-4e7e-bdda-3866177ff838 died, removing from map.
    ERROR:root:kernel 3d08514d-4d39-4e7e-bdda-3866177ff838 restarted failed!
    [W 08:50:29.929 NotebookApp] Kernel deleted before session
    [W 08:50:29.929 NotebookApp] 410 DELETE /api/sessions/19f3b3e6-80a1-48f4-a201-d069f471ae7a (::1) 2.07ms referer=http://localhost:8888/notebooks/notebooks/01-map.ipynb

**Comment by michaelpacer** [comment]
Ok I think it has something to do with the conda's ipykernel not being picked up before a previous version of ipykernel that was installed relative to a brew installed version of `python3`.

I'm going to try to uninstall the brewed version of python and only use the conda python install…

after doing that I ran into a bunch of errors, which were much more explicit… and I'm fairly certain it has to do with the conda version of python being shielded

**Comment by jasongrout** [comment]
Mixing and matching brew and conda is a bad idea. When you install jupyterlab, you should enable it with `--sys-prefix` to make sure it stays in the environment it was installed in.

Closing, but please open another issue if it still isn't working when you try just using conda.

**Comment by jbwhit** [comment]
I had this same problem, and I didn't install python via brew.

This is what I see when I start up `jupyter notebook`:

```
[W 12:03:30.010 NotebookApp] Error loading server extension jupyterlab
    Traceback (most recent call last):
      File "/Users/jonathan/miniconda2/envs/py3/lib/python3.5/site-packages/notebook/notebookapp.py", line 1046, in init_server_extensions
        mod = importlib.import_module(modulename)
      File "/Users/jonathan/miniconda2/envs/py3/lib/python3.5/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 986, in _gcd_import
      File "<frozen importlib._bootstrap>", line 969, in _find_and_load
      File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
    ImportError: No module named 'jupyterlab'
```

But I didn't have the problem where it killed new kernels. 

There is some tension between what @jasongrout wrote above:

> When you install jupyterlab, you should enable it with --sys-prefix to make sure it stays in the environment it was installed in.

And what the Readme currently says: 

```
pip install jupyterlab
jupyter serverextension enable --py jupyterlab
```

Should this be updated in the Readme?
