### ISSUE TITLE
``npm install`` failing with latest Node installed

### ISSUE THREAD

**Issue by palewire** [jupyter/jupyterlab#403]
Trying to follow your installation instructions from the README I encountered the following error during ``npm install``. I believe I have Node 6+ and the latest NPM installed. But please tell me if there's user error involved. 

```python
ben@stumbo ~/Code/jupyterlab/jupyterlab
 % npm install                         

> jupyterlab@0.0.12 prepublish /home/ben/Code/jupyterlab
> npm run build


> jupyterlab@0.0.12 build /home/ben/Code/jupyterlab
> npm run build:src


> jupyterlab@0.0.12 build:src /home/ben/Code/jupyterlab
> tsc --project src && node scripts/copyfiles.js

sh: 1: tsc: not found

npm ERR! Linux 4.4.0-28-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build:src"
npm ERR! node v6.3.0
npm ERR! npm  v3.10.3
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! jupyterlab@0.0.12 build:src: `tsc --project src && node scripts/copyfiles.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the jupyterlab@0.0.12 build:src script 'tsc --project src && node scripts/copyfiles.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the jupyterlab package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc --project src && node scripts/copyfiles.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs jupyterlab
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls jupyterlab
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ben/Code/jupyterlab/npm-debug.log

npm ERR! Linux 4.4.0-28-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
npm ERR! node v6.3.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! jupyterlab@0.0.12 build: `npm run build:src`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the jupyterlab@0.0.12 build script 'npm run build:src'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the jupyterlab package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build:src
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs jupyterlab
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls jupyterlab
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ben/Code/jupyterlab/npm-debug.log
npm ERR! addLocal Could not install /home/ben/Code/jupyterlab
npm WARN Local package.json exists, but node_modules missing, did you mean to install?
npm ERR! Linux 4.4.0-28-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v6.3.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! jupyterlab@0.0.12 prepublish: `npm run build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the jupyterlab@0.0.12 prepublish script 'npm run build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the jupyterlab package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs jupyterlab
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls jupyterlab
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ben/Code/jupyterlab/jupyterlab/npm-debug.log
```

**Comment by blink1073** [comment]
It looks like the dev dependencies were not installed, you must have the `NODE_ENV` variable set to production.

**Comment by palewire** [comment]
Ah. Thank you. That might be a good add to your README. I'll continue with my installation and consider a pull request if I can get things working.

**Comment by jasongrout** [comment]
@SylvainCorlay also has a similar problem from time to time, though I forget what we decided was the problem.

**Comment by jasongrout** [comment]
@palewire, is it working now? It may be that we decided that @SylvainCorlay had an old version of node, and updating to a newer version of node fixed his problem.

**Comment by drussellmrichie** [comment]
I'm not sure whether I should make a new issue, or just post here. [I'm still new to posting issues on github (and, well, new at most things).] I guess I'll just post here. I'm also having difficulties with "npm install". I am running Node 6.3.0 (installed with brew) and npm 3.10.3.

```
russellrichie@Russells-MacBook-Pro:~/jupyterlab$ sudo npm install
npm WARN lifecycle jupyterlab@0.1.1~postinstall: cannot run in wd %s %s (wd=%s) jupyterlab@0.1.1 npm dedupe /Users/russellrichie/jupyterlab
npm WARN lifecycle jupyterlab@0.1.1~prepublish: cannot run in wd %s %s (wd=%s) jupyterlab@0.1.1 npm run build /Users/russellrichie/jupyterlab
jupyterlab@0.1.1 /Users/russellrichie/jupyterlab
└─┬ css-loader@0.23.1
  └─┬ cssnano@3.7.3
    └─┬ postcss-svgo@2.1.4
      └── svgo@0.6.6 

npm WARN enoent ENOENT, open '/Users/russellrichie/jupyterlab/node_modules/clap/package.json'
```

I figured "okay, just warnings, not errors....let's try the next step". So I did, but it crashed:

```
russellrichie@Russells-MacBook-Pro:~/jupyterlab$ pip install -e .
Obtaining file:///Users/russellrichie/jupyterlab
    Complete output from command python setup.py egg_info:
    setup.py entered
    running egg_info
    running jsdeps
    3.10.3
    Installing extension build dependencies with npm.  This may take a while...
    
    > jupyterlab@0.1.1 prepublish /Users/russellrichie/jupyterlab
    > npm run build
    
    
    > jupyterlab@0.1.1 build /Users/russellrichie/jupyterlab
    > npm run build:src
    
    
    > jupyterlab@0.1.1 build:src /Users/russellrichie/jupyterlab
    > tsc --project src && node scripts/copyfiles.js
    
    node_modules/phosphor-widget/lib/widget.d.ts(17,22): error TS2420: Class 'Widget' incorrectly implements interface 'IMessageHandler'.
      Types of property 'compressMessage' are incompatible.
        Type '(msg: Message, pending: Queue<Message>) => boolean' is not assignable to type '(msg: Message, pending: Queue<Message>) => boolean'.
          Types of parameters 'pending' and 'pending' are incompatible.
            Type 'Queue<Message>' is not assignable to type 'Queue<Message>'.
              Types have separate declarations of a private property '_size'.
    src/docmanager/widgetmanager.ts(99,26): error TS2345: Argument of type 'Widget' is not assignable to parameter of type 'IMessageHandler'.
      Types of property 'compressMessage' are incompatible.
        Type '(msg: Message, pending: Queue<Message>) => boolean' is not assignable to type '(msg: Message, pending: Queue<Message>) => boolean'.
    src/docmanager/widgetmanager.ts(195,20): error TS2352: Neither type 'IMessageHandler' nor type 'Widget' is assignable to the other.
      Property 'dispose' is missing in type 'IMessageHandler'.
    src/terminal/index.ts(263,17): error TS2345: Argument of type 'this' is not assignable to parameter of type 'IMessageHandler'.
      Type 'TerminalWidget' is not assignable to type 'IMessageHandler'.
        Types of property 'compressMessage' are incompatible.
          Type '(msg: Message, pending: Queue<Message>) => boolean' is not assignable to type '(msg: Message, pending: Queue<Message>) => boolean'.
    
    npm ERR! Darwin 15.5.0
    npm ERR! argv "node" "/usr/local/bin/npm" "run" "build:src"
    npm ERR! node v0.10.34
    npm ERR! npm  v3.10.3
    npm ERR! code ELIFECYCLE
    npm ERR! jupyterlab@0.1.1 build:src: `tsc --project src && node scripts/copyfiles.js`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the jupyterlab@0.1.1 build:src script 'tsc --project src && node scripts/copyfiles.js'.
    npm ERR! Make sure you have the latest version of node.js and npm installed.
    npm ERR! If you do, this is most likely a problem with the jupyterlab package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     tsc --project src && node scripts/copyfiles.js
    npm ERR! You can get information on how to open an issue for this project with:
    npm ERR!     npm bugs jupyterlab
    npm ERR! Or if that isn't available, you can get their info via:
    npm ERR!     npm owner ls jupyterlab
    npm ERR! There is likely additional logging output above.
    
    npm ERR! Please include the following file with any support request:
    npm ERR!     /Users/russellrichie/jupyterlab/npm-debug.log
    
    npm ERR! Darwin 15.5.0
    npm ERR! argv "node" "/usr/local/bin/npm" "run" "build"
    npm ERR! node v0.10.34
    npm ERR! npm  v3.10.3
    npm ERR! code ELIFECYCLE
    npm ERR! jupyterlab@0.1.1 build: `npm run build:src`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the jupyterlab@0.1.1 build script 'npm run build:src'.
    npm ERR! Make sure you have the latest version of node.js and npm installed.
    npm ERR! If you do, this is most likely a problem with the jupyterlab package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     npm run build:src
    npm ERR! You can get information on how to open an issue for this project with:
    npm ERR!     npm bugs jupyterlab
    npm ERR! Or if that isn't available, you can get their info via:
    npm ERR!     npm owner ls jupyterlab
    npm ERR! There is likely additional logging output above.
    
    npm ERR! Please include the following file with any support request:
    npm ERR!     /Users/russellrichie/jupyterlab/npm-debug.log
    npm ERR! addLocal Could not install /Users/russellrichie/jupyterlab
    npm WARN Local package.json exists, but node_modules missing, did you mean to install?
    npm ERR! Darwin 15.5.0
    npm ERR! argv "node" "/usr/local/bin/npm" "install"
    npm ERR! node v0.10.34
    npm ERR! npm  v3.10.3
    npm ERR! code ELIFECYCLE
    
    npm ERR! jupyterlab@0.1.1 prepublish: `npm run build`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the jupyterlab@0.1.1 prepublish script 'npm run build'.
    npm ERR! Make sure you have the latest version of node.js and npm installed.
    npm ERR! If you do, this is most likely a problem with the jupyterlab package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     npm run build
    npm ERR! You can get information on how to open an issue for this project with:
    npm ERR!     npm bugs jupyterlab
    npm ERR! Or if that isn't available, you can get their info via:
    npm ERR!     npm owner ls jupyterlab
    npm ERR! There is likely additional logging output above.
    
    npm ERR! Please include the following file with any support request:
    npm ERR!     /Users/russellrichie/jupyterlab/jupyterlab/npm-debug.log
    //anaconda/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'License'
      warnings.warn(msg)
    rebuilding js and css failed
    missing files: ['/Users/russellrichie/jupyterlab/jupyterlab/build/bundle.js']
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/russellrichie/jupyterlab/setup.py", line 158, in <module>
        setup(**setup_args)
      File "//anaconda/lib/python3.5/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "//anaconda/lib/python3.5/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "//anaconda/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/Users/russellrichie/jupyterlab/setup.py", line 54, in run
        raise e
      File "/Users/russellrichie/jupyterlab/setup.py", line 47, in run
        self.distribution.run_command('jsdeps')
      File "//anaconda/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/Users/russellrichie/jupyterlab/setup.py", line 101, in run
        run('npm install', cwd=extension_root)
      File "/Users/russellrichie/jupyterlab/setup.py", line 28, in run
        check_call(cmd.split(), shell=shell, cwd=cwd, stdout=sys.stdout, stderr=sys.stderr)
      File "//anaconda/lib/python3.5/subprocess.py", line 581, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['npm', 'install']' returned non-zero exit status 1
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /Users/russellrichie/jupyterlab/
```

Any clue what's going on here?

**Comment by jasongrout** [comment]
@drussellmrichie, it looks like on https://github.com/jupyter/jupyterlab/issues/408, you figured it out.

**Comment by drussellmrichie** [comment]
@jasongrout, that's right. Thanks for keeping an eye out!

**Comment by jasongrout** [comment]
Great. Closing this, then.

**Comment by jasongrout** [comment]
Actually, I should wait for @palewire to confirm that it works for them now.

**Comment by jasongrout** [comment]
Re-closing this. @palewire, I think we covered all of the problems on this and the other referenced issues. If things are still not working, please re-open this if it seems like it's the same problem, or open another issue if it seems like a new problem.
