### ISSUE TITLE
npm ERR! Error: No compatible version found: jupyterlab@'file:../'

### ISSUE THREAD

**Issue by dbl001** [jupyter/jupyterlab#437]
Ubuntu 14.04 LTS
$ pip --version
pip 8.1.2 from /home/ubuntu/anaconda/lib/python2.7/site-packages (python 2.7)
$ npm --version
1.3.10

$ pip install -e .
Obtaining file:///home/ubuntu/jupyterlab
    Complete output from command python setup.py egg_info:
    setup.py entered
    /home/ubuntu/anaconda/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'License'
      warnings.warn(msg)
    running egg_info
    running jsdeps
    1.3.10
    Installing extension build dependencies with npm.  This may take a while...
    npm http GET https://registry.npmjs.org/font-awesome
    npm http GET https://registry.npmjs.org/es6-promise
    npm http GET https://registry.npmjs.org/jupyter-js-widgets-labextension
    npm http GET https://registry.npmjs.org/jupyterlab
    npm http GET https://registry.npmjs.org/material-design-icons
    npm http GET https://registry.npmjs.org/jupyter-js-services
    npm http GET https://registry.npmjs.org/phosphide
    npm http GET https://registry.npmjs.org/css-loader
    npm http GET https://registry.npmjs.org/file-loader
    npm http GET https://registry.npmjs.org/json-loader
    npm http GET https://registry.npmjs.org/rimraf
    npm http GET https://registry.npmjs.org/style-loader
    npm http GET https://registry.npmjs.org/url-loader
    npm http GET https://registry.npmjs.org/webpack
    npm http GET https://registry.npmjs.org/typescript
    npm http 304 https://registry.npmjs.org/jupyter-js-widgets-labextension
    npm http 304 https://registry.npmjs.org/material-design-icons
    npm http 304 https://registry.npmjs.org/phosphide
    npm http 304 https://registry.npmjs.org/font-awesome
    npm http 304 https://registry.npmjs.org/jupyterlab
    npm http 304 https://registry.npmjs.org/es6-promise
    npm http 304 https://registry.npmjs.org/rimraf
    npm http 304 https://registry.npmjs.org/jupyter-js-services
    npm http 304 https://registry.npmjs.org/file-loader
    npm http 304 https://registry.npmjs.org/url-loader
    npm http 304 https://registry.npmjs.org/css-loader
    npm http 304 https://registry.npmjs.org/webpack
    npm http 304 https://registry.npmjs.org/style-loader
    npm http 304 https://registry.npmjs.org/json-loader
    npm http 304 https://registry.npmjs.org/typescript
    npm ERR! Error: No compatible version found: jupyterlab@'file:../'
    npm ERR! Valid install targets:
    npm ERR! ["0.0.1","0.0.2","0.0.3","0.0.4","0.0.5","0.0.6","0.0.7","0.0.8","0.0.9","0.0.10","0.0.11","0.0.12","0.0.13","0.1.0","0.1.1"]
    npm ERR!     at installTargetsError (/usr/share/npm/lib/cache.js:719:10)
    npm ERR!     at /usr/share/npm/lib/cache.js:638:10
    npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:142:7)
    npm ERR!     at /usr/lib/nodejs/graceful-fs/polyfills.js:133:7
    npm ERR!     at Object.oncomplete (fs.js:107:15)
    npm ERR! If you need help, you may report this log at:
    npm ERR!     <http://github.com/isaacs/npm/issues>
    npm ERR! or email it to:
    npm ERR!     <npm-@googlegroups.com>
    
    npm ERR! System Linux 3.13.0-92-generic
    npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
    npm ERR! cwd /home/ubuntu/jupyterlab/jupyterlab
    npm ERR! node -v v0.10.25
    npm ERR! npm -v 1.3.10
    npm ERR!
    npm ERR! Additional logging details can be found in:
    npm ERR!     /home/ubuntu/jupyterlab/jupyterlab/npm-debug.log
    npm ERR! not ok code 0
    rebuilding js and css failed
    missing files: ['/home/ubuntu/jupyterlab/jupyterlab/build/bundle.js']
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/ubuntu/jupyterlab/setup.py", line 158, in <module>
        setup(**setup_args)
      File "/home/ubuntu/anaconda/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/home/ubuntu/anaconda/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/home/ubuntu/anaconda/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/home/ubuntu/jupyterlab/setup.py", line 54, in run
        raise e
    subprocess.CalledProcessError: Command '['npm', 'install']' returned non-zero exit status 1
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /home/ubuntu/jupyterlab/

**Comment by sccolbert** [comment]
Is this from a fresh clone of master?

**Comment by sccolbert** [comment]
i.e. what did you do before `pip install -e`?

**Comment by dbl001** [comment]
Yes.  
1. Fresh clone.
2. npm install

After that didn’t work I tried:
1. git clean -dfx
2. npm run build:all
3. npm install
4. pip install -e .

**Comment by afshin** [comment]
@dbl001 Is your build still broken? Your version of npm is very old. If your build is still not working, could you try upgrading your node and npm? Otherwise, does this issue need to remain open?

Thanks!

**Comment by dbl001** [comment]
David-Laxers-MacBook-Pro:coursera davidlaxer$ port list npm
npm                            @2.15.3         devel/npm

Should I use ‘npm2’?

David-Laxers-MacBook-Pro:coursera davidlaxer$ sudo port install npm2
--->  Computing dependencies for npm2
--->  Fetching archive for npm2
--->  Attempting to fetch npm2-2.15.9_0.darwin_15.noarch.tbz2 from https://packages.macports.org/npm2
--->  Attempting to fetch npm2-2.15.9_0.darwin_15.noarch.tbz2.rmd160 from https://packages.macports.org/npm2
--->  Installing npm2 @2.15.9_0
--->  Activating npm2 @2.15.9_0
Error: org.macports.activate for port npm2 returned: Image error: /opt/local/lib/node_modules/npm/lib/utils/get-publish-config.js already exists and does not belong to a registered port.  Unable to activate port npm2. Use 'port -f activate npm2' to force the activation.
Please see the log file for port npm2 for details:
    /opt/local/var/macports/logs/_opt_local_var_macports_sources_rsync.macports.org_release_tarballs_ports_devel_npm2/npm2/main.log
To report a bug, follow the instructions in the guide:
    http://guide.macports.org/#project.tickets
Error: Processing of port npm2 failed
David-Laxers-MacBook-Pro:coursera davidlaxer$

**Comment by afshin** [comment]
`npm` no longer needs to be installed on its own, it now comes bundled with node js. If I were you, I would consider uninstall the MacPorts version:
```
port uninstall npm
port uninstall nodejs
```

And then just installing via the installer on https://nodejs.org/

**Comment by jasongrout** [comment]
Closing because of inactivity. If it still isn't working for you, please reopen and we can continue helping you.
