### ISSUE TITLE
source install error (win64)

### ISSUE THREAD

**Issue by dhirschfeld** [jupyter/jupyterlab#491]
Is anyone else seeing this?
```
λ pip install -e .
Obtaining file:///C:/dev/packages/jupyterlab
    Complete output from command python setup.py egg_info:
    setup.py entered
    running egg_info
    running jsdeps
    3.7.3
    Installing extension build dependencies with npm.  This may take a while...

    > jupyterlab@0.1.1 prepublish C:\dev\packages\jupyterlab
    > npm run build


    > jupyterlab@0.1.1 build C:\dev\packages\jupyterlab
    > npm run build:src


    > jupyterlab@0.1.1 build:src C:\dev\packages\jupyterlab
    > tsc --project src && node scripts/copyfiles.js

    npm ERR! cb() never called!
    C:\Python\lib\distutils\dist.py:261: UserWarning: Unknown distribution option: 'License'
      warnings.warn(msg)
    rebuilding js and css failed
    missing files: ['C:\\dev\\packages\\jupyterlab\\jupyterlab\\build\\bundle.js']
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\dev\packages\jupyterlab\setup.py", line 158, in <module>
        setup(**setup_args)
      File "C:\Python\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Python\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "C:\Python\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\dev\packages\jupyterlab\setup.py", line 54, in run
        raise e
      File "C:\dev\packages\jupyterlab\setup.py", line 47, in run
        self.distribution.run_command('jsdeps')
      File "C:\Python\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\dev\packages\jupyterlab\setup.py", line 101, in run
        run('npm install', cwd=extension_root)
      File "C:\dev\packages\jupyterlab\setup.py", line 28, in run
        check_call(cmd.split(), shell=shell, cwd=cwd, stdout=sys.stdout, stderr=sys.stderr)
      File "C:\Python\lib\subprocess.py", line 581, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['npm', 'install']' returned non-zero exit status 1
```

**Comment by blink1073** [comment]
Hi @dhirschfeld, can you please try running the command `npm install` from the root repository directory?

**Comment by dhirschfeld** [comment]
I did run `npm install` before the `pip install -e .` with the above result. I also retried after doing an `npm cache clean` with no joy.

Have just pulled the latest master and retried, again with no luck :(
```
λ npm install

> jupyterlab@0.1.1 postinstall C:\dev\packages\jupyterlab
> npm dedupe


> jupyterlab@0.1.1 prepublish C:\dev\packages\jupyterlab
> npm run build


> jupyterlab@0.1.1 build C:\dev\packages\jupyterlab
> npm run build:src


> jupyterlab@0.1.1 build:src C:\dev\packages\jupyterlab
> tsc --project src && node scripts/copyfiles.js

- jupyter-js-utils@0.4.0 node_modules\jupyter-js-utils
jupyterlab@0.1.1 C:\dev\packages\jupyterlab
`-- jupyter-js-services@0.16.0
  `-- path-posix@1.0.0

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
C:\dev\packages\jupyterlab [master ≡]
λ pip install -e .
Obtaining file:///C:/dev/packages/jupyterlab
    Complete output from command python setup.py egg_info:
    setup.py entered
    running egg_info
    running jsdeps
    3.7.3
    Installing extension build dependencies with npm.  This may take a while...

    > jupyterlab@0.1.1 prepublish C:\dev\packages\jupyterlab
    > npm run build


    > jupyterlab@0.1.1 build C:\dev\packages\jupyterlab
    > npm run build:src


    > jupyterlab@0.1.1 build:src C:\dev\packages\jupyterlab
    > tsc --project src && node scripts/copyfiles.js

    npm ERR! cb() never called!
    C:\Python\lib\distutils\dist.py:261: UserWarning: Unknown distribution option: 'License'
      warnings.warn(msg)
    rebuilding js and css failed
    missing files: ['C:\\dev\\packages\\jupyterlab\\jupyterlab\\build\\bundle.js']
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\dev\packages\jupyterlab\setup.py", line 158, in <module>
        setup(**setup_args)
      File "C:\Python\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Python\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "C:\Python\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\dev\packages\jupyterlab\setup.py", line 54, in run
        raise e
      File "C:\dev\packages\jupyterlab\setup.py", line 47, in run
        self.distribution.run_command('jsdeps')
      File "C:\Python\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\dev\packages\jupyterlab\setup.py", line 101, in run
        run('npm install', cwd=extension_root)
      File "C:\dev\packages\jupyterlab\setup.py", line 28, in run
        check_call(cmd.split(), shell=shell, cwd=cwd, stdout=sys.stdout, stderr=sys.stderr)
      File "C:\Python\lib\subprocess.py", line 581, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['npm', 'install']' returned non-zero exit status 1

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\dev\packages\jupyterlab\
```

**Comment by dhirschfeld** [comment]
```
λ node --version
v5.9.0
C:\dev\packages\jupyterlab [master ≡]
λ npm --version
3.7.3
```
Python 3.5 on win64

**Comment by jasongrout** [comment]
Something is jogging in my memory about windows not setting the path when invoking a subprocess, so you have to do some magic to get it to find the right commands, or invoke the commands directly. That may be what is happening here.

**Comment by dhirschfeld** [comment]
My previous issue was due to not setting shell=true on the subprocess.
Perhaps it's the same problem?

**Comment by jasongrout** [comment]
Oh yeah, I forgot that was a solution.

**Comment by jasongrout** [comment]
I wonder if this is not being triggered: https://github.com/jupyter/jupyterlab/blob/8999bee631c471c9e6fe653b053c52988854e1cd/setup.py#L27

**Comment by jasongrout** [comment]
Can you check to see if shell is true in your case, by inserting a print statement or something?

**Comment by dhirschfeld** [comment]
It definitely *should* be:
```ipython
In [3]: sys.platform
Out[3]: 'win32'
```
...and it seems that it is:
```
λ git diff
diff --git a/setup.py b/setup.py
index 82b8454..f3b6b20 100644
--- a/setup.py
+++ b/setup.py
@@ -25,6 +25,7 @@ def run(cmd, cwd=None):
     """
     # On Windows, shell should be True so that the path is searched for the command.
     shell = (sys.platform == 'win32')
+    print("shell={} ".format(shell) + '<'*70)
     check_call(cmd.split(), shell=shell, cwd=cwd, stdout=sys.stdout, stderr=sys.stderr)

 from distutils import log
C:\dev\packages\jupyterlab [master ≡ +0 ~1 -0 !]
λ pip install -e .
Obtaining file:///C:/dev/packages/jupyterlab
    Complete output from command python setup.py egg_info:
    setup.py entered
    running egg_info
    running jsdeps
    3.7.3
    shell=True <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
    Installing extension build dependencies with npm.  This may take a while...

    > jupyterlab@0.1.1 prepublish C:\dev\packages\jupyterlab
    > npm run build


    > jupyterlab@0.1.1 build C:\dev\packages\jupyterlab
    > npm run build:src


    > jupyterlab@0.1.1 build:src C:\dev\packages\jupyterlab
    > tsc --project src && node scripts/copyfiles.js

    npm ERR! cb() never called!
    C:\Python\lib\distutils\dist.py:261: UserWarning: Unknown distribution option: 'License'
      warnings.warn(msg)
    rebuilding js and css failed
    missing files: ['C:\\dev\\packages\\jupyterlab\\jupyterlab\\build\\bundle.js']
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\dev\packages\jupyterlab\setup.py", line 159, in <module>
        setup(**setup_args)
      File "C:\Python\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Python\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "C:\Python\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\dev\packages\jupyterlab\setup.py", line 55, in run
        raise e
      File "C:\dev\packages\jupyterlab\setup.py", line 48, in run
        self.distribution.run_command('jsdeps')
      File "C:\Python\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\dev\packages\jupyterlab\setup.py", line 102, in run
        run('npm install', cwd=extension_root)
      File "C:\dev\packages\jupyterlab\setup.py", line 29, in run
        check_call(cmd.split(), shell=shell, cwd=cwd, stdout=sys.stdout, stderr=sys.stderr)
      File "C:\Python\lib\subprocess.py", line 581, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['npm', 'install']' returned non-zero exit status 1
    shell=True <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\dev\packages\jupyterlab\
```

**Comment by jasongrout** [comment]
Oh, I guess the real error is `npm ERR! cb() never called!`. Google indicates that doing `sudo npm cache clean` fixes this. Can you try that?

**Comment by jasongrout** [comment]
This is a more drastic solution: http://www.saintsatplay.com/blog/2015/03/resolving-npm-err-cb-never-called-errors

**Comment by dhirschfeld** [comment]
Saw that and have already done a `npm cache clean` before retrying with no luck

**Comment by dhirschfeld** [comment]
No joy there - I did an `npm cache clean`, deleted my `C:\Users\dhirschf\AppData\Roaming\npm` folder and retried with the same result :/

**Comment by dhirschfeld** [comment]
I nuked the local `lib` and `node_modules` folders and retried `npm install` which seemed to work - output [here](https://gist.github.com/dhirschfeld/a26754a7359f166611df59711669ba2a#file-jupyterlab_npm_install_output)

I added some more instrumentation to the `setup.py` and re-ran the `pip install -e .` command but still got the same `cb() never called` error with no more info.
```
C:\dev\packages\jupyterlab [master ≡ +0 ~1 -0 !]
λ git diff
diff --git a/setup.py b/setup.py
index 82b8454..e8e76f3 100644
--- a/setup.py
+++ b/setup.py
@@ -23,9 +23,19 @@ def run(cmd, cwd=None):

     >>> run('npm install', cwd='./subdir')
     """
+    from subprocess import Popen, PIPE
     # On Windows, shell should be True so that the path is searched for the command.
     shell = (sys.platform == 'win32')
-    check_call(cmd.split(), shell=shell, cwd=cwd, stdout=sys.stdout, stderr=sys.stderr)
+    proc = Popen(cmd.split(), shell=shell, cwd=cwd, stdout=PIPE, stderr=PIPE)
+    stdout, stderr = proc.communicate()
+    print(stdout.decode('utf-8'))
+    if proc.returncode != 0:
+        msg = (
+            "The processes exited with returncode {}\n".format(proc.returncode),
+            "cmd='{}'\n".format(cmd)
+        )
+        raise Exception('\n'.join(msg) + stderr.decode('utf-8'))

λ pip install -e .
Obtaining file:///C:/dev/packages/jupyterlab
    Complete output from command python setup.py egg_info:
    setup.py entered
    running egg_info
    running jsdeps
    3.7.3

    Installing extension build dependencies with npm.  This may take a while...
    C:\Python\lib\distutils\dist.py:261: UserWarning: Unknown distribution option: 'License'
      warnings.warn(msg)
    rebuilding js and css failed
    missing files: ['C:\\dev\\packages\\jupyterlab\\jupyterlab\\build\\bundle.js']
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\dev\packages\jupyterlab\setup.py", line 168, in <module>
        setup(**setup_args)
      File "C:\Python\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Python\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "C:\Python\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\dev\packages\jupyterlab\setup.py", line 64, in run
        raise e
      File "C:\dev\packages\jupyterlab\setup.py", line 57, in run
        self.distribution.run_command('jsdeps')
      File "C:\Python\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\dev\packages\jupyterlab\setup.py", line 111, in run
        run('npm install', cwd=extension_root)
      File "C:\dev\packages\jupyterlab\setup.py", line 37, in run
        raise Exception('\n'.join(msg) + stderr.decode('utf-8'))
    Exception: The processes exited with returncode 1

    cmd='npm install'
    npm ERR! cb() never called!


    > jupyterlab@0.1.1 prepublish C:\dev\packages\jupyterlab
    > npm run build


    > jupyterlab@0.1.1 build C:\dev\packages\jupyterlab
    > npm run build:src


    > jupyterlab@0.1.1 build:src C:\dev\packages\jupyterlab
    > tsc --project src && node scripts/copyfiles.js



    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\dev\packages\jupyterlab\
```

**Comment by jasongrout** [comment]
another thing to try: `python -c "from subprocess import check_call; check_call('where npm*', shell=True)"`

Maybe the npm available from python is different than your system npm. I know anaconda sometimes does funny things with npm.

**Comment by jasongrout** [comment]
and if that works, does the one command in setup.py work? 

```
python -c "from subprocess import check_call; check_call('npm install', shell=True)"
```

**Comment by dhirschfeld** [comment]
I've only got the one node installed, checked anyway to confirm.

It seems to be a common problem - https://github.com/jfromaniello/npm-install-retry

**Comment by dhirschfeld** [comment]
I read some messages saying upgrading to >= 5.10 fixed the problem so I have just installed the latest v6.3.0 and it seems to be working - hasn't errored out yet...

**Comment by jasongrout** [comment]
hooray! The joys of npm packaging :)

**Comment by dhirschfeld** [comment]
Indeed :stuck_out_tongue_winking_eye:

The install did work so I'm closing this as it's not a jupyter problem. At least this thread might help someone else...

**Comment by jasongrout** [comment]
Whew, good job figuring it out!
