### ISSUE TITLE
Bug with Terminal Plugin

### ISSUE THREAD

**Issue by charnpreetsingh185** [jupyter/jupyterlab#501]
Repeatedly opening and shutting down terminals results in an exception in the server.

Here's a console log:

charnpreet@wsp035086wss ~/D/jupyterlab> jupyter lab
[W 11:18:18.886 LabApp] Unrecognized JSON config file version, assuming version 1
[I 11:18:19.065 LabApp] It looks like you're running JupyterLab from source.
    If you're working on the TypeScript sources of JupyterLab, try running
    
        npm run watch
    
    from the JupyterLab repo directory in another terminal window to have the system
    incrementally watch and build JupyterLab's TypeScript for you, as you make
    changes.
    
[I 11:18:19.065 LabApp] JupyterLab alpha preview extension loaded from /Users/charnpreet/Desktop/jupyterlab/jupyterlab
[I 11:18:19.069 LabApp] Serving notebooks from local directory: /Users/charnpreet/Desktop/jupyterlab
[I 11:18:19.069 LabApp] 0 active kernels 
[I 11:18:19.069 LabApp] The Jupyter Notebook is running at: http://localhost:8888/
[I 11:18:19.069 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 11:18:40.672 LabApp] New terminal with automatic name: 1
[I 11:18:41.842 LabApp] New terminal with automatic name: 2
[I 11:18:45.749 LabApp] EOF on FD 17; stopping reading
[I 11:18:45.749 LabApp] Terminal 1 closed
[I 11:18:48.188 LabApp] EOF on FD 19; stopping reading
[I 11:18:48.189 LabApp] Terminal 2 closed
[I 11:18:53.367 LabApp] New terminal with automatic name: 1
[I 11:18:54.336 LabApp] New terminal with automatic name: 2
[I 11:18:55.346 LabApp] New terminal with automatic name: 3
[I 11:18:58.925 LabApp] EOF on FD 21; stopping reading
[I 11:18:58.926 LabApp] Terminal 3 closed
[I 11:19:00.956 LabApp] EOF on FD 17; stopping reading
[I 11:19:00.957 LabApp] Terminal 1 closed
[I 11:19:02.085 LabApp] EOF on FD 19; stopping reading
[I 11:19:02.086 LabApp] Terminal 2 closed
[I 11:19:08.071 LabApp] New terminal with automatic name: 1
[I 11:19:10.423 LabApp] New terminal with automatic name: 2
[I 11:19:14.334 LabApp] EOF on FD 19; stopping reading
[I 11:19:14.334 LabApp] Terminal 2 closed
[I 11:19:16.502 LabApp] EOF on FD 17; stopping reading
[I 11:19:16.502 LabApp] Terminal 1 closed
[I 11:19:21.503 LabApp] New terminal with automatic name: 1
[I 11:19:22.142 LabApp] New terminal with automatic name: 2
[I 11:19:29.126 LabApp] EOF on FD 19; stopping reading
[I 11:19:29.126 LabApp] Terminal 2 closed
[I 11:19:32.415 LabApp] New terminal with automatic name: 2
[I 11:19:34.837 LabApp] EOF on FD 17; stopping reading
[I 11:19:34.838 LabApp] Terminal 1 closed
[I 11:19:35.774 LabApp] EOF on FD 19; stopping reading
[I 11:19:35.774 LabApp] Terminal 2 closed
[I 11:19:40.447 LabApp] New terminal with automatic name: 1
[I 11:19:41.350 LabApp] New terminal with automatic name: 2
[I 11:19:42.095 LabApp] New terminal with automatic name: 3
[E 11:19:42.418 LabApp] Exception in callback (17, <function wrap.<locals>.null_wrapper at 0x104e46950>)
    Traceback (most recent call last):
      File "/Users/charnpreet/anaconda/lib/python3.5/site-packages/tornado/ioloop.py", line 883, in start
        handler_func(fd_obj, events)
      File "/Users/charnpreet/anaconda/lib/python3.5/site-packages/tornado/stack_context.py", line 275, in null_wrapper
        return fn(*args, **kwargs)
      File "/Users/charnpreet/anaconda/lib/python3.5/site-packages/terminado/management.py", line 187, in pty_read
        s = ptywclients.ptyproc.read(65536)
      File "/Users/charnpreet/anaconda/lib/python3.5/site-packages/ptyprocess/ptyprocess.py", line 803, in read
        b = super(PtyProcessUnicode, self).read(size)
      File "/Users/charnpreet/anaconda/lib/python3.5/site-packages/ptyprocess/ptyprocess.py", line 507, in read
        s = self.fileobj.read(size)
    OSError: [Errno 9] Bad file descriptor
[E 11:19:42.420 LabApp] Exception in callback (19, <function wrap.<locals>.null_wrapper at 0x104c7f400>)
    Traceback (most recent call last):
      File "/Users/charnpreet/anaconda/lib/python3.5/site-packages/tornado/ioloop.py", line 883, in start
        handler_func(fd_obj, events)
      File "/Users/charnpreet/anaconda/lib/python3.5/site-packages/tornado/stack_context.py", line 275, in null_wrapper
        return fn(*args, **kwargs)
      File "/Users/charnpreet/anaconda/lib/python3.5/site-packages/terminado/management.py", line 187, in pty_read
        s = ptywclients.ptyproc.read(65536)
      File "/Users/charnpreet/anaconda/lib/python3.5/site-packages/ptyprocess/ptyprocess.py", line 803, in read
        b = super(PtyProcessUnicode, self).read(size)
      File "/Users/charnpreet/anaconda/lib/python3.5/site-packages/ptyprocess/ptyprocess.py", line 507, in read
        s = self.fileobj.read(size)
    OSError: [Errno 9] Bad file descriptor
[E 11:19:42.420 LabApp] Exception in callback (21, <function wrap.<locals>.null_wrapper at 0x104e4d620>)
    Traceback (most recent call last):
      File "/Users/charnpreet/anaconda/lib/python3.5/site-packages/tornado/ioloop.py", line 883, in start
        handler_func(fd_obj, events)
      File "/Users/charnpreet/anaconda/lib/python3.5/site-packages/tornado/stack_context.py", line 275, in null_wrapper
        return fn(*args, **kwargs)
      File "/Users/charnpreet/anaconda/lib/python3.5/site-packages/terminado/management.py", line 187, in pty_read
        s = ptywclients.ptyproc.read(65536)
      File "/Users/charnpreet/anaconda/lib/python3.5/site-packages/ptyprocess/ptyprocess.py", line 803, in read
        b = super(PtyProcessUnicode, self).read(size)
      File "/Users/charnpreet/anaconda/lib/python3.5/site-packages/ptyprocess/ptyprocess.py", line 507, in read
        s = self.fileobj.read(size)
    OSError: [Errno 9] Bad file descriptor
[E 11:19:42.420 LabApp] Exception in callback (17, <function wrap.<locals>.null_wrapper at 0x104e46950>)
    Traceback (most recent call last):
      File "/Users/charnpreet/anaconda/lib/python3.5/site-packages/tornado/ioloop.py", line 883, in start
        handler_func(fd_obj, events)
      File "/Users/charnpreet/anaconda/lib/python3.5/site-packages/tornado/stack_context.py", line 275, in null_wrapper
        return fn(*args, **kwargs)
      File "/Users/charnpreet/anaconda/lib/python3.5/site-packages/terminado/management.py", line 187, in pty_read
        s = ptywclients.ptyproc.read(65536)
      File "/Users/charnpreet/anaconda/lib/python3.5/site-packages/ptyprocess/ptyprocess.py", line 803, in read
        b = super(PtyProcessUnicode, self).read(size)
      File "/Users/charnpreet/anaconda/lib/python3.5/site-packages/ptyprocess/ptyprocess.py", line 507, in read
        s = self.fileobj.read(size)
    OSError: [Errno 9] Bad file descriptor
[E 11:19:42.421 LabApp] Exception in callback (19, <function wrap.<locals>.null_wrapper at 0x104c7f400>)
    Traceback (most recent call last):
      File "/Users/charnpreet/anaconda/lib/python3.5/site-packages/tornado/ioloop.py", line 883, in start
        handler_func(fd_obj, events)
      File "/Users/charnpreet/anaconda/lib/python3.5/site-packages/tornado/stack_context.py", line 275, in null_wrapper
        return fn(*args, **kwargs)
      File "/Users/charnpreet/anaconda/lib/python3.5/site-packages/terminado/management.py", line 187, in pty_read
        s = ptywclients.ptyproc.read(65536)
      File "/Users/charnpreet/anaconda/lib/python3.5/site-packages/ptyprocess/ptyprocess.py", line 803, in read
        b = super(PtyProcessUnicode, self).read(size)
      File "/Users/charnpreet/anaconda/lib/python3.5/site-packages/ptyprocess/ptyprocess.py", line 507, in read
        s = self.fileobj.read(size)
    OSError: [Errno 9] Bad file descriptor

**Comment by blink1073** [comment]
Hmm, I'm not able to reproduce this.  I was able to start and stop a dozen terminals a few times.

I am running with the latest master of notebook and jupyterlab, `Python 3.4.4 |Anaconda 2.4.1 (x86_64)| (default, Jan  9 2016, 17:30:09)`.

**Comment by sccolbert** [comment]
@charnpreetsingh185 if you can reproduce, can you do screen capture of the process?

**Comment by charnpreetsingh185** [comment]
Yes, I'll try to do that.  How did you get Python/Anaconda version info?

**Comment by charnpreetsingh185** [comment]
![terminalbug](https://cloud.githubusercontent.com/assets/16314651/17040146/1c4d78a2-4f53-11e6-8df6-4aded4718e91.gif)

**Comment by blink1073** [comment]
My guess is that `terminado` has a race condition somewhere that is resulting in a read from a process that has already closed.  Thoughts, @takluyver?

**Comment by takluyver** [comment]
I think @charnpreetsingh185 has an old version of terminado, based on the line number in the traceback above. This sounds very similar to takluyver/terminado#13, which was fixed by takluyver/terminado#24, and released as 0.6.

**Comment by blink1073** [comment]
@charnpreetsingh185, can you please run `conda install terminado` to upgrade and try again?  (or `pip install -U terminado` if you aren't using conda).

**Comment by charnpreetsingh185** [comment]
Thanks @takluyver @blink1073 that seems to have fixed it. I'm going to close this issue then...
