### ISSUE TITLE
conda-forge install just leads to 404

### ISSUE THREAD

**Issue by michaelaye** [jupyter/jupyterlab#509]
Here's my setup procedure:

* create new python3.5 conda env for playing with jupyterlab
* `conda install -c conda-forge jupyterlab` (getting 0.1.1)
* launching via `jupyter lab` as told by scipy talk
terminal log:
```zsh
Enabling: jupyterlab ]|                                                   |   0%
- Writing config: /Users/klay6683/miniconda3/envs/jupyterlab/etc/jupyter
    - Validating...
      jupyterlab  OK
[      COMPLETE      ]|###################################################| 100%

┌─( ~/D/src )───────────────────────────────────────────────────( @MacL2938 )─┐
(jupyterlab) └─❱❱❱ jupyter lab                                  +4649 22:52 ❰─┘
[W 22:52:28.001 LabApp] Unrecognized JSON config file version, assuming version 1
[I 22:52:30.739 LabApp] Serving notebooks from local directory: /Users/klay6683/Dropbox/src
[I 22:52:30.740 LabApp] 0 active kernels
[I 22:52:30.740 LabApp] The Jupyter Notebook is running at: http://localhost:8888/
[I 22:52:30.740 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 22:52:32.867 LabApp] 404 GET /lab (127.0.0.1) 113.98ms referer=None
[W 22:52:33.558 LabApp] 404 GET /apple-touch-icon-precomposed.png (127.0.0.1) 3.40ms referer=None
[W 22:52:33.571 LabApp] 404 GET /apple-touch-icon.png (127.0.0.1) 5.50ms referer=None
[W 22:52:33.871 LabApp] 404 GET /apple-touch-icon-precomposed.png (127.0.0.1) 5.05ms referer=None
[W 22:52:33.880 LabApp] 404 GET /apple-touch-icon.png (127.0.0.1) 6.32ms referer=None
[W 22:52:33.921 LabApp] 404 GET /apple-touch-icon-precomposed.png (127.0.0.1) 5.17ms referer=None
[W 22:52:33.925 LabApp] 404 GET /apple-touch-icon.png (127.0.0.1) 1.22ms referer=None
[W 22:52:49.706 LabApp] 404 GET /lab (127.0.0.1) 1.90ms referer=None
[W 22:52:49.881 LabApp] 404 GET /apple-touch-icon-precomposed.png (127.0.0.1) 1.77ms referer=None
[W 22:52:49.885 LabApp] 404 GET /apple-touch-icon.png (127.0.0.1) 1.49ms referer=None
[W 22:54:19.829 LabApp] 404 GET /lab (::1) 11.35ms referer=None
```
but Safari 9.1.1 just shows 404 page:
![screenshot 2016-07-21 22 57 26](https://cloud.githubusercontent.com/assets/69774/17047016/89178764-4f96-11e6-89d9-8828d54b70bb.png)

**Comment by jasongrout** [comment]
Can you write down the *exact* command sequence you did? It looks like jupyterlab is not being registered in the current environment, since the notebook didn't indicate it was loaded as an extension.

**Comment by michaelaye** [comment]
Do you need the exact commands for creating the new conda env? (because that takes a while as i have many dependencies, pip libs and private libs i install in there, via scripts), or how I installed and launched jupyterlab?
The latter would be (as written above):
```bash
conda install -c conda-forge jupyterlab
jupyter lab
```

**Comment by jasongrout** [comment]
I was looking for anything that seemed out of the ordinary, like forgetting to activate the environment or something. I was hoping for a minimal example. 

Are you on Windows, OS X, or something else?

This works for me (on OS X); does the equivalent work for you?

```
conda create -n issue509 python=3
source activate issue509
conda install -c conda-forge jupyterlab
jupyter lab
```

**Comment by michaelaye** [comment]
With your example I get:
```bash
(issue509) └─❱❱❱ jupyter lab                                                         +6092 12:28 ❰─┘
[W 12:28:50.089 LabApp] Unrecognized JSON config file version, assuming version 1
[W 12:28:50.835 LabApp] Widgets are unavailable. Please install widgetsnbextension or ipywidgets 4.0
[I 12:28:50.839 LabApp] The port 8901 is already in use, trying another port.
[W 12:28:50.861 LabApp] Error loading server extension nbextensions
    Traceback (most recent call last):
      File "/Users/klay6683/miniconda3/envs/issue509/lib/python3.5/site-packages/notebook/notebookapp.py", line 1046, in init_server_extensions
        mod = importlib.import_module(modulename)
      File "/Users/klay6683/miniconda3/envs/issue509/lib/python3.5/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 986, in _gcd_import
      File "<frozen importlib._bootstrap>", line 969, in _find_and_load
      File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 665, in exec_module
      File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
      File "/Users/klay6683/Library/Jupyter/extensions/nbextensions.py", line 16, in <module>
        import yaml
    ImportError: No module named 'yaml'
[I 12:28:50.887 LabApp] Serving notebooks from local directory: /Users/klay6683/Dropbox/src
[I 12:28:50.887 LabApp] 0 active kernels
[I 12:28:50.887 LabApp] The Jupyter Notebook is running at: https://[all ip addresses on your system]:8902/
[I 12:28:50.887 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
```

**Comment by jasongrout** [comment]
Okay, I think you have extensions installed in your user directory; maybe those are messing things up. Can you do `jupyter nbextension list` and `jupyter serverextension list`?

**Comment by michaelaye** [comment]
Ah yes, I have quite a few stuff installed:
```zsh
(issue509) └─❱❱❱ jupyter nbextension list                                            +6095 13:54 ❰─┘
Known nbextensions:
  config dir: /Users/klay6683/.jupyter/nbconfig
    notebook section
      livereveal/main  enabled
      - Validating: OK
      usability/autoscroll/main  enabled
      - Validating: OK
    tree section
      ipyparallel/main  enabled
      - Validating: OK

┌─( ~/D/s/pyciss_work λ:master | ✱ ◼ b04d491 )───────────────────────────────────────( @macd2860 )─┐
(issue509) └─❱❱❱ jupyter serverextension list                                        +6096 13:54 ❰─┘
config dir: /Users/klay6683/.jupyter
    nbextensions  enabled
    - Validating...
Error loading server extension nbextensions
      X is nbextensions importable?
config dir: /Users/klay6683/miniconda3/envs/issue509/etc/jupyter
    jupyterlab  enabled
    - Validating...
      jupyterlab  OK
```

**Comment by blink1073** [comment]
@michaelaye, does `conda install yaml` clear up the error with `jupyter serverextension list`?  It looks like it may also clear up your `jupyter lab` error.

**Comment by michaelaye** [comment]
No, it didn't. But there were so many changes recently with nbextensions (new jupyter extension configurator that i didn't have yet, etc), I decided to dump my jupyter config and start from scratch. Moving .jupyter and $JUPYTER_DATA_DIR/nbextensions makes `jupyter lab` run. So I guess we can archive this under old_config_mess or something. I'm fine with closing this issue.

**Comment by blink1073** [comment]
Been there before.  Glad it is working for you now!
