### ISSUE TITLE
jupyterlab clashes with nb_conda_kernels

### ISSUE THREAD

**Issue by michaelaye** [jupyter/jupyterlab#523]
I am using `nb_conda_kernels` to find automatically my installed conda environments and their ipython kernels.
I just discovered that a new Python 3.5 environment with the only addition of jupyterlab runs fine, while just adding nb_conda_kernels from conda-forge will  break something and the jupyterlab won't launch, instead showing me a grey tab in Safari 9.1.2 (OSX 10.10.5), without any error message.
The console log complains though:
```zsh
(jupyterlab) └─❱❱❱ jupyter lab                                                       +6171 17:29 ❰─┘
[W 17:29:40.192 LabApp] Unrecognized JSON config file version, assuming version 1
[W 17:29:40.196 LabApp] Unrecognized JSON config file version, assuming version 1
[W 17:29:40.196 LabApp] server_extensions is deprecated, use nbserver_extensions
[I 17:29:40.603 LabApp] [nb_conda_kernels] enabled, 5 kernels found
[W 17:29:40.618 LabApp] Widgets are unavailable. Please install widgetsnbextension or ipywidgets 4.0
[W 17:29:40.627 LabApp] Error loading server extension ipyparallel.nbextension
    Traceback (most recent call last):
      File "/Users/klay6683/miniconda3/envs/jupyterlab/lib/python3.5/site-packages/notebook/notebookapp.py", line 1046, in init_server_extensions
        mod = importlib.import_module(modulename)
      File "/Users/klay6683/miniconda3/envs/jupyterlab/lib/python3.5/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 986, in _gcd_import
      File "<frozen importlib._bootstrap>", line 969, in _find_and_load
      File "<frozen importlib._bootstrap>", line 944, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
      File "<frozen importlib._bootstrap>", line 986, in _gcd_import
      File "<frozen importlib._bootstrap>", line 969, in _find_and_load
      File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
    ImportError: No module named 'ipyparallel'
[I 17:29:40.627 LabApp] Pre-alpha version of JupyterLab extension loaded from /Users/klay6683/miniconda3/envs/jupyterlab/lib/python3.5/site-packages/jupyterlab
[I 17:29:40.631 LabApp] Serving notebooks from local directory: /Users/klay6683
[I 17:29:40.631 LabApp] 0 active kernels
[I 17:29:40.631 LabApp] The Jupyter Notebook is running at: http://localhost:8888/
[I 17:29:40.631 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
```
My install procedure was:

* conda create -n jupyterlab python=3
* source activate jupyterlab
* conda install -c conda-forge jupyterlab

Trying `jupyter lab` now works fine.
But adding:

* conda install -c conda-forge nb_conda_kernels

breaks things.

**Comment by blink1073** [comment]
Hmm, it looks like you still might have some missing config left over, this is similar to the type of error we saw on your machine earlier.  Your recourse might be to clear all of the config directories listed in `jupyter paths`.  FWIW, I just tried installing `nb_conda_kernels` in my environment, and it worked fine.

```
Python 3.4.5 | packaged by conda-forge | (default, Jul  9 2016, 18:00:48)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.54)] on darwin
```

**Comment by michaelaye** [comment]
Weird, I did exactly that. Lemme try again.

**Comment by michaelaye** [comment]
Ok, my logs are now error free, but I get the same issue, that with `nb_conda_kernels` installed launching `jupyter lab` just gives me a gray tab. It's very repeatable, as soon as i do `conda remove nb_conda_kernels`, `jupyter lab` launch works again.
I run things in both cases, with the `--debug` switch on, for some reason the version with `nb_conda_kernels` installed, seems to end prematurely?

Running things without  `nb_conda_kernels` installed:
```zsh
(jupyterlabpy34) └─❱❱❱ jupyter lab --debug                                     +4630 22:34 ❰─┘
[D 22:34:45.268 LabApp] Searching ['/Users/klay6683', '/Users/klay6683/.jupyter', '/Users/klay6683/miniconda3/envs/jupyterlabpy34/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
[D 22:34:45.268 LabApp] Looking for jupyter_config in /etc/jupyter
[D 22:34:45.269 LabApp] Looking for jupyter_config in /usr/local/etc/jupyter
[D 22:34:45.269 LabApp] Looking for jupyter_config in /Users/klay6683/miniconda3/envs/jupyterlabpy34/etc/jupyter
[D 22:34:45.269 LabApp] Looking for jupyter_config in /Users/klay6683/.jupyter
[D 22:34:45.269 LabApp] Looking for jupyter_config in /Users/klay6683
[D 22:34:45.270 LabApp] Looking for jupyter_notebook_config in /etc/jupyter
[D 22:34:45.270 LabApp] Looking for jupyter_notebook_config in /usr/local/etc/jupyter
[D 22:34:45.270 LabApp] Looking for jupyter_notebook_config in /Users/klay6683/miniconda3/envs/jupyterlabpy34/etc/jupyter
[W 22:34:45.270 LabApp] Unrecognized JSON config file version, assuming version 1
[D 22:34:45.270 LabApp] Loaded config file: /Users/klay6683/miniconda3/envs/jupyterlabpy34/etc/jupyter/jupyter_notebook_config.json
[D 22:34:45.271 LabApp] Looking for jupyter_notebook_config in /Users/klay6683/.jupyter
[D 22:34:45.272 LabApp] Looking for jupyter_notebook_config in /Users/klay6683
[W 22:34:45.294 LabApp] Widgets are unavailable. Please install widgetsnbextension or ipywidgets 4.0
[I 22:34:45.305 LabApp] Pre-alpha version of JupyterLab extension loaded from /Users/klay6683/miniconda3/envs/jupyterlabpy34/lib/python3.4/site-packages/jupyterlab
[I 22:34:45.309 LabApp] Serving notebooks from local directory: /Users/klay6683
[I 22:34:45.309 LabApp] 0 active kernels
[I 22:34:45.309 LabApp] The Jupyter Notebook is running at: http://localhost:8888/
[I 22:34:45.309 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[D 22:34:47.850 LabApp] Using contents: services/contents
[D 22:34:47.862 LabApp] 200 GET /lab (::1) 14.80ms
[D 22:34:47.906 LabApp] 304 GET /static/components/MathJax/MathJax.js?config=TeX-AMS_HTML-full,Safe&delayStartupUntil=configured (::1) 2.57ms
[D 22:34:47.911 LabApp] 304 GET /static/components/jquery-ui/ui/minified/jquery-ui.min.js?v=fb4770e78488812ef9f99b7c7484688d (::1) 1.15ms
[D 22:34:47.913 LabApp] 304 GET /static/components/jquery/jquery.min.js?v=ccd0edd113b78697e04fb5c1b519a5cd (::1) 0.87ms
[D 22:34:47.916 LabApp] 304 GET /lab/bundle.js (::1) 2.22ms
[D 22:34:47.940 LabApp] 304 GET /static/components/MathJax/config/TeX-AMS_HTML-full.js?rev=2.6.0 (::1) 1.46ms
[D 22:34:48.390 LabApp] 304 GET /static/components/MathJax/config/Safe.js?rev=2.6.0 (::1) 1.06ms
[D 22:34:48.411 LabApp] Native kernel (python3) available from /Users/klay6683/miniconda3/envs/jupyterlabpy34/lib/python3.4/site-packages/ipykernel/resources
[D 22:34:48.412 LabApp] Native kernel (python3) available from /Users/klay6683/miniconda3/envs/jupyterlabpy34/lib/python3.4/site-packages/ipykernel/resources
[D 22:34:48.413 LabApp] 200 GET /api/kernelspecs?1469421288404 (::1) 6.73ms
[D 22:34:48.452 LabApp] 200 GET /api/contents?content=1&1469421288417 (::1) 32.31ms
[D 22:34:48.455 LabApp] 304 GET /lab/2b609d364e2e1d67ba33a81c58d9eb8a.svg (::1) 1.22ms
[D 22:34:48.457 LabApp] 200 GET /api/terminals?1469421288425 (::1) 1.18ms
[D 22:34:48.461 LabApp] 200 GET /api/sessions?1469421288454 (::1) 2.51ms
[D 22:34:48.463 LabApp] 304 GET /lab/a5f896d73c05dd2cec16fd54f7b6d38b.svg (::1) 1.90ms
[D 22:34:48.465 LabApp] 304 GET /lab/67210cba51efc06308353fa274b6d389.svg (::1) 0.95ms
[D 22:34:48.468 LabApp] 304 GET /lab/c8ddf1e5e5bf3682bc7bebf30f394148.woff (::1) 1.56ms
[D 22:34:48.470 LabApp] 200 GET /api/sessions?1469421288460 (::1) 0.89ms
[D 22:34:58.490 LabApp] 200 GET /api/contents?content=1&1469421298467 (::1) 20.23ms
[D 22:34:58.493 LabApp] 200 GET /api/sessions?1469421298491 (::1) 0.68ms
[D 22:34:58.538 LabApp] 200 GET /api/terminals?1469421298534 (::1) 1.36ms
[D 22:34:58.543 LabApp] 200 GET /api/sessions?1469421298540 (::1) 0.67ms
[D 22:35:08.521 LabApp] 200 GET /api/contents?content=1&1469421308499 (::1) 19.09ms
[D 22:35:08.526 LabApp] 200 GET /api/sessions?1469421308524 (::1) 0.91ms
[D 22:35:08.550 LabApp] 200 GET /api/terminals?1469421308545 (::1) 1.72ms
[D 22:35:08.569 LabApp] 200 GET /api/sessions?1469421308567 (::1) 0.70ms
[D 22:35:18.547 LabApp] 200 GET /api/contents?content=1&1469421318529 (::1) 16.47ms
[D 22:35:18.552 LabApp] 200 GET /api/sessions?1469421318549 (::1) 0.96ms
[D 22:35:18.579 LabApp] 200 GET /api/terminals?1469421318575 (::1) 1.65ms
[D 22:35:18.584 LabApp] 200 GET /api/sessions?1469421318581 (::1) 0.88ms
```

Running things with `nb_conda_kernels` installed:
```zsh
(jupyterlabpy34) └─❱❱❱ jupyter lab --debug                                                  +4632 22:36 ❰─┘
[D 22:36:32.697 LabApp] Searching ['/Users/klay6683', '/Users/klay6683/.jupyter', '/Users/klay6683/miniconda3/envs/jupyterlabpy34/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
[D 22:36:32.697 LabApp] Looking for jupyter_config in /etc/jupyter
[D 22:36:32.698 LabApp] Looking for jupyter_config in /usr/local/etc/jupyter
[D 22:36:32.698 LabApp] Looking for jupyter_config in /Users/klay6683/miniconda3/envs/jupyterlabpy34/etc/jupyter
[D 22:36:32.698 LabApp] Looking for jupyter_config in /Users/klay6683/.jupyter
[D 22:36:32.698 LabApp] Looking for jupyter_config in /Users/klay6683
[D 22:36:32.699 LabApp] Looking for jupyter_notebook_config in /etc/jupyter
[D 22:36:32.699 LabApp] Looking for jupyter_notebook_config in /usr/local/etc/jupyter
[D 22:36:32.699 LabApp] Looking for jupyter_notebook_config in /Users/klay6683/miniconda3/envs/jupyterlabpy34/etc/jupyter
[W 22:36:32.700 LabApp] Unrecognized JSON config file version, assuming version 1
[D 22:36:32.700 LabApp] Loaded config file: /Users/klay6683/miniconda3/envs/jupyterlabpy34/etc/jupyter/jupyter_notebook_config.json
[D 22:36:32.704 LabApp] Looking for jupyter_notebook_config in /Users/klay6683/.jupyter
[D 22:36:32.705 LabApp] Looking for jupyter_notebook_config in /Users/klay6683
[D 22:36:32.718 LabApp] Native kernel (python3) available from /Users/klay6683/miniconda3/envs/jupyterlabpy34/lib/python3.4/site-packages/ipykernel/resources
[I 22:36:32.998 LabApp] [nb_conda_kernels] enabled, 2 kernels found
[D 22:36:32.998 LabApp]
    - Python [jupyterlabpy34]: /Users/klay6683/miniconda3/envs/jupyterlabpy34/bin/python
    - Python [stable]: /Users/klay6683/miniconda3/envs/stable/bin/python
[W 22:36:33.031 LabApp] Widgets are unavailable. Please install widgetsnbextension or ipywidgets 4.0
[I 22:36:33.050 LabApp] Pre-alpha version of JupyterLab extension loaded from /Users/klay6683/miniconda3/envs/jupyterlabpy34/lib/python3.4/site-packages/jupyterlab
[I 22:36:33.056 LabApp] Serving notebooks from local directory: /Users/klay6683
[I 22:36:33.056 LabApp] 0 active kernels
[I 22:36:33.057 LabApp] The Jupyter Notebook is running at: http://localhost:8888/
[I 22:36:33.057 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[D 22:36:33.415 LabApp] Using contents: services/contents
[D 22:36:33.448 LabApp] 304 GET /lab (::1) 40.94ms
[D 22:36:33.521 LabApp] 304 GET /static/components/MathJax/MathJax.js?config=TeX-AMS_HTML-full,Safe&delayStartupUntil=configured (::1) 4.33ms
[D 22:36:33.571 LabApp] 304 GET /static/components/MathJax/config/TeX-AMS_HTML-full.js?rev=2.6.0 (::1) 3.41ms
[D 22:36:33.667 LabApp] 200 GET /lab/bundle.js (::1) 145.83ms
[D 22:36:33.714 LabApp] 304 GET /static/components/MathJax/config/Safe.js?rev=2.6.0 (::1) 1.12ms
[D 22:36:34.402 LabApp] Native kernel (python3) available from /Users/klay6683/miniconda3/envs/jupyterlabpy34/lib/python3.4/site-packages/ipykernel/resources
[D 22:36:34.694 LabApp] 200 GET /api/kernelspecs?1469421394400 (::1) 292.37ms
```

To be closer to your example, I did this all with Python3.4:
```zsh
(jupyterlabpy34) └─❱❱❱ python                                                               +4633 22:46 ❰─┘
Python 3.4.5 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:47:57)
[GCC 4.2.1 Compatible Apple LLVM 4.2 (clang-425.0.28)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

**Comment by blink1073** [comment]
@michaelaye, I tried with an as-identical setup as I could, Safari, OSX, Python 3.4.5, and it works.
Is there anything printed in the JavaScript console (Option + Command + I will bring it up).

**Comment by michaelaye** [comment]
No errors. :(
Did you confirm with running the jupyter server in `--debug` mode if you see the same differences in the log?

**Comment by blink1073** [comment]
Here's my output:

```
[I 11:18:14.251 LabApp] JupyterLab alpha preview extension loaded from /Users/ssilvester/workspace/jupyter/lab/jupyterlab
[I 11:18:14.255 LabApp] Serving notebooks from local directory: /Users/ssilvester/Downloads
[I 11:18:14.255 LabApp] 0 active kernels
[I 11:18:14.255 LabApp] The Jupyter Notebook is running at: http://localhost:8888/
[I 11:18:14.255 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[D 11:18:14.529 LabApp] Using contents: services/built/contents
[D 11:18:14.538 LabApp] 304 GET /lab (::1) 10.59ms
/Users/ssilvester/workspace/jupyter/notebook/notebook/static/
/Users/ssilvester/workspace/jupyter/notebook/notebook/static/components/MathJax/MathJax.js
[D 11:18:14.633 LabApp] 304 GET /static/components/MathJax/MathJax.js?config=TeX-AMS_HTML-full,Safe&delayStartupUntil=configured (::1) 1.30ms
/Users/ssilvester/workspace/jupyter/lab/jupyterlab/build/
/Users/ssilvester/workspace/jupyter/lab/jupyterlab/build/bundle.js
[D 11:18:14.635 LabApp] 304 GET /lab/bundle.js (::1) 0.73ms
/Users/ssilvester/workspace/jupyter/notebook/notebook/static/
/Users/ssilvester/workspace/jupyter/notebook/notebook/static/components/MathJax/config/TeX-AMS_HTML-full.js
[D 11:18:14.690 LabApp] 304 GET /static/components/MathJax/config/TeX-AMS_HTML-full.js?rev=2.6.0 (::1) 0.83ms
/Users/ssilvester/workspace/jupyter/notebook/notebook/static/
/Users/ssilvester/workspace/jupyter/notebook/notebook/static/components/MathJax/config/Safe.js
[D 11:18:14.765 LabApp] 304 GET /static/components/MathJax/config/Safe.js?rev=2.6.0 (::1) 1.00ms
[D 11:18:15.248 LabApp] Found kernel calysto_bash in /Users/ssilvester/Library/Jupyter/kernels
[D 11:18:15.248 LabApp] Found kernel calysto_xonsh in /Users/ssilvester/Library/Jupyter/kernels
[D 11:18:15.248 LabApp] Found kernel scilab in /Users/ssilvester/Library/Jupyter/kernels
[D 11:18:15.248 LabApp] Found kernel octave in /Users/ssilvester/Library/Jupyter/kernels
[D 11:18:15.249 LabApp] Found kernel xonsh in /Users/ssilvester/anaconda/share/jupyter/kernels
[D 11:18:15.249 LabApp] Found kernel matlab in /usr/local/share/jupyter/kernels
[D 11:18:15.249 LabApp] Found kernel python3 in /usr/local/share/jupyter/kernels
[D 11:18:15.690 LabApp] Found kernel calysto_bash in /Users/ssilvester/Library/Jupyter/kernels
[D 11:18:15.691 LabApp] Found kernel calysto_xonsh in /Users/ssilvester/Library/Jupyter/kernels
[D 11:18:15.691 LabApp] Found kernel scilab in /Users/ssilvester/Library/Jupyter/kernels
[D 11:18:15.691 LabApp] Found kernel octave in /Users/ssilvester/Library/Jupyter/kernels
[D 11:18:15.691 LabApp] Found kernel xonsh in /Users/ssilvester/anaconda/share/jupyter/kernels
[D 11:18:15.691 LabApp] Found kernel matlab in /usr/local/share/jupyter/kernels
[D 11:18:15.691 LabApp] Found kernel python3 in /usr/local/share/jupyter/kernels
[D 11:18:16.163 LabApp] Found kernel calysto_bash in /Users/ssilvester/Library/Jupyter/kernels
[D 11:18:16.163 LabApp] Found kernel calysto_xonsh in /Users/ssilvester/Library/Jupyter/kernels
[D 11:18:16.163 LabApp] Found kernel scilab in /Users/ssilvester/Library/Jupyter/kernels
[D 11:18:16.163 LabApp] Found kernel octave in /Users/ssilvester/Library/Jupyter/kernels
[D 11:18:16.163 LabApp] Found kernel xonsh in /Users/ssilvester/anaconda/share/jupyter/kernels
[D 11:18:16.163 LabApp] Found kernel matlab in /usr/local/share/jupyter/kernels
[D 11:18:16.163 LabApp] Found kernel python3 in /usr/local/share/jupyter/kernels
[D 11:18:16.551 LabApp] Found kernel calysto_bash in /Users/ssilvester/Library/Jupyter/kernels
[D 11:18:16.551 LabApp] Found kernel calysto_xonsh in /Users/ssilvester/Library/Jupyter/kernels
[D 11:18:16.551 LabApp] Found kernel scilab in /Users/ssilvester/Library/Jupyter/kernels
[D 11:18:16.551 LabApp] Found kernel octave in /Users/ssilvester/Library/Jupyter/kernels
[D 11:18:16.551 LabApp] Found kernel xonsh in /Users/ssilvester/anaconda/share/jupyter/kernels
[D 11:18:16.551 LabApp] Found kernel matlab in /usr/local/share/jupyter/kernels
[D 11:18:16.551 LabApp] Found kernel python3 in /usr/local/share/jupyter/kernels
[D 11:18:16.943 LabApp] Found kernel calysto_bash in /Users/ssilvester/Library/Jupyter/kernels
[D 11:18:16.944 LabApp] Found kernel calysto_xonsh in /Users/ssilvester/Library/Jupyter/kernels
[D 11:18:16.944 LabApp] Found kernel scilab in /Users/ssilvester/Library/Jupyter/kernels
[D 11:18:16.944 LabApp] Found kernel octave in /Users/ssilvester/Library/Jupyter/kernels
[D 11:18:16.944 LabApp] Found kernel xonsh in /Users/ssilvester/anaconda/share/jupyter/kernels
[D 11:18:16.944 LabApp] Found kernel matlab in /usr/local/share/jupyter/kernels
[D 11:18:16.944 LabApp] Found kernel python3 in /usr/local/share/jupyter/kernels
[D 11:18:17.334 LabApp] Found kernel calysto_bash in /Users/ssilvester/Library/Jupyter/kernels
[D 11:18:17.334 LabApp] Found kernel calysto_xonsh in /Users/ssilvester/Library/Jupyter/kernels
[D 11:18:17.334 LabApp] Found kernel scilab in /Users/ssilvester/Library/Jupyter/kernels
[D 11:18:17.334 LabApp] Found kernel octave in /Users/ssilvester/Library/Jupyter/kernels
[D 11:18:17.334 LabApp] Found kernel xonsh in /Users/ssilvester/anaconda/share/jupyter/kernels
[D 11:18:17.334 LabApp] Found kernel matlab in /usr/local/share/jupyter/kernels
[D 11:18:17.334 LabApp] Found kernel python3 in /usr/local/share/jupyter/kernels
[D 11:18:17.724 LabApp] Found kernel calysto_bash in /Users/ssilvester/Library/Jupyter/kernels
[D 11:18:17.724 LabApp] Found kernel calysto_xonsh in /Users/ssilvester/Library/Jupyter/kernels
[D 11:18:17.724 LabApp] Found kernel scilab in /Users/ssilvester/Library/Jupyter/kernels
[D 11:18:17.724 LabApp] Found kernel octave in /Users/ssilvester/Library/Jupyter/kernels
[D 11:18:17.724 LabApp] Found kernel xonsh in /Users/ssilvester/anaconda/share/jupyter/kernels
[D 11:18:17.724 LabApp] Found kernel matlab in /usr/local/share/jupyter/kernels
[D 11:18:17.725 LabApp] Found kernel python3 in /usr/local/share/jupyter/kernels
[D 11:18:18.114 LabApp] 200 GET /api/kernelspecs?1469463495245 (::1) 2865.90ms
[D 11:18:18.175 LabApp] 200 GET /api/contents?content=1&1469463498138 (::1) 35.06ms
/Users/ssilvester/workspace/jupyter/lab/jupyterlab/build/
/Users/ssilvester/workspace/jupyter/lab/jupyterlab/build/2b609d364e2e1d67ba33a81c58d9eb8a.svg
[D 11:18:18.176 LabApp] 304 GET /lab/2b609d364e2e1d67ba33a81c58d9eb8a.svg (::1) 0.50ms
[D 11:18:18.177 LabApp] 200 GET /api/terminals?1469463498149 (::1) 0.53ms
/Users/ssilvester/workspace/jupyter/lab/jupyterlab/build/
/Users/ssilvester/workspace/jupyter/lab/jupyterlab/build/e6cf7c6ec7c2d6f670ae9d762604cb0b.woff2
[D 11:18:18.178 LabApp] 304 GET /lab/e6cf7c6ec7c2d6f670ae9d762604cb0b.woff2 (::1) 0.55ms
/Users/ssilvester/workspace/jupyter/lab/jupyterlab/build/
/Users/ssilvester/workspace/jupyter/lab/jupyterlab/build/67210cba51efc06308353fa274b6d389.svg
[D 11:18:18.179 LabApp] 304 GET /lab/67210cba51efc06308353fa274b6d389.svg (::1) 0.46ms
/Users/ssilvester/workspace/jupyter/lab/jupyterlab/build/
/Users/ssilvester/workspace/jupyter/lab/jupyterlab/build/a5f896d73c05dd2cec16fd54f7b6d38b.svg
[D 11:18:18.179 LabApp] 304 GET /lab/a5f896d73c05dd2cec16fd54f7b6d38b.svg (::1) 0.42ms
[D 11:18:18.241 LabApp] 200 GET /api/sessions?1469463498234 (::1) 1.53ms
[D 11:18:18.242 LabApp] 200 GET /api/sessions?1469463498237 (::1) 0.81ms
```

The only thing I can think may be wrong is you might have an older version of `jupyter-js-services` loaded.  What is the output of `npm list | grep services` from the root of the repo?

**Comment by michaelaye** [comment]
I am confused which repo are you talking about? All my activities were done via conda?

**Comment by blink1073** [comment]
Ah, I had made the assumption that you were working from the git repository.  It looks like we are due for a release.

**Comment by michaelaye** [comment]
aha, guess what, with jupyterlab GH master it works also with `nb_conda_kernels`. my fault, i should have started the issue with more precise version descriptions of what I'm using. Thanks for your engagement!
