### ISSUE TITLE
Labextension CLI exception for help

### ISSUE THREAD

**Issue by vidartf** [jupyter/jupyterlab#935]
Running ` jupyter labextension install --help` gives the following traceback after printing (parts of?) the normal help text.
```python
> jupyter labextension install --help
Install JupyterLab extensions

<snip normal output>

--debug
    set log level to logging.DEBUG (maximize logging output)
--sys-prefix
    Use sys.prefix as the prefix for installing labextensions (for environments, packaging)
Traceback (most recent call last):
  File "C:\Miniconda3\Scripts\jupyter-labextension-script.py", line 9, in <module>
    load_entry_point('jupyterlab==0.3.0', 'console_scripts', 'jupyter-labextension')()
  File "c:\miniconda3\lib\site-packages\jupyter_core\application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "c:\miniconda3\lib\site-packages\traitlets\config\application.py", line 595, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-6>", line 2, in initialize
  File "c:\miniconda3\lib\site-packages\traitlets\config\application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "c:\miniconda3\lib\site-packages\jupyter_core\application.py", line 239, in initialize
    self.parse_command_line(argv)
  File "<decorator-gen-4>", line 2, in parse_command_line
  File "c:\miniconda3\lib\site-packages\traitlets\config\application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "c:\miniconda3\lib\site-packages\traitlets\config\application.py", line 488, in parse_command_line
    return self.initialize_subcommand(subc, subargv)
  File "<decorator-gen-3>", line 2, in initialize_subcommand
  File "c:\miniconda3\lib\site-packages\traitlets\config\application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "c:\miniconda3\lib\site-packages\traitlets\config\application.py", line 426, in initialize_subcommand
    self.subapp.initialize(argv)
  File "<decorator-gen-6>", line 2, in initialize
  File "c:\miniconda3\lib\site-packages\traitlets\config\application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "c:\miniconda3\lib\site-packages\jupyter_core\application.py", line 239, in initialize
    self.parse_command_line(argv)
  File "<decorator-gen-4>", line 2, in parse_command_line
  File "c:\miniconda3\lib\site-packages\traitlets\config\application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "c:\miniconda3\lib\site-packages\traitlets\config\application.py", line 500, in parse_command_line
    self.print_help('--help-all' in interpreted_argv)
  File "c:\miniconda3\lib\site-packages\traitlets\config\application.py", line 360, in print_help
    self.print_options()
  File "c:\miniconda3\lib\site-packages\traitlets\config\application.py", line 331, in print_options
    self.print_alias_help()
  File "c:\miniconda3\lib\site-packages\traitlets\config\application.py", line 297, in print_alias_help
    trait = cls.class_traits(config=True)[traitname]
KeyError: 'destination'
```

**Comment by vidartf** [comment]
Partly related: Running `jupyter lab --help` still has a few left overs from copy-paste from notebook, e.g. the examples section.
